In [4]:
from tensorflow.keras.preprocessing.text import one_hot

In [5]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [6]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [7]:
## Define the vocabulary size
voc_size=10000

In [8]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [9]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[16, 6188, 8514, 7784],
 [16, 6188, 8514, 4003],
 [16, 5146, 8514, 241],
 [9224, 123, 5142, 8825, 6378],
 [9224, 123, 5142, 8825, 931],
 [9686, 16, 5282, 8514, 8894],
 [5940, 811, 7306, 8825]]

In [13]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [14]:
import numpy as np

In [15]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0   16 6188 8514 7784]
 [   0    0    0    0   16 6188 8514 4003]
 [   0    0    0    0   16 5146 8514  241]
 [   0    0    0 9224  123 5142 8825 6378]
 [   0    0    0 9224  123 5142 8825  931]
 [   0    0    0 9686   16 5282 8514 8894]
 [   0    0    0    0 5940  811 7306 8825]]


In [16]:
## feature representation
dim=10

In [17]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

2025-01-31 12:34:32.213006: I metal_plugin/src/device/metal_device.cc:1154] Metal device set to: Apple M3 Pro
2025-01-31 12:34:32.213232: I metal_plugin/src/device/metal_device.cc:296] systemMemory: 18.00 GB
2025-01-31 12:34:32.213252: I metal_plugin/src/device/metal_device.cc:313] maxCacheSize: 6.00 GB
2025-01-31 12:34:32.213464: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:306] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2025-01-31 12:34:32.213803: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:272] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)


In [18]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [19]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 215ms/step


2025-01-31 12:35:38.811043: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:117] Plugin optimizer for device_type GPU is enabled.


array([[[ 0.0444671 , -0.02529125,  0.0149972 , -0.01539929,
          0.00635128,  0.02066917, -0.00046979,  0.03555099,
         -0.03456575, -0.017493  ],
        [ 0.0444671 , -0.02529125,  0.0149972 , -0.01539929,
          0.00635128,  0.02066917, -0.00046979,  0.03555099,
         -0.03456575, -0.017493  ],
        [ 0.0444671 , -0.02529125,  0.0149972 , -0.01539929,
          0.00635128,  0.02066917, -0.00046979,  0.03555099,
         -0.03456575, -0.017493  ],
        [ 0.0444671 , -0.02529125,  0.0149972 , -0.01539929,
          0.00635128,  0.02066917, -0.00046979,  0.03555099,
         -0.03456575, -0.017493  ],
        [-0.02394995,  0.01773771,  0.00273856,  0.03932923,
         -0.04540272,  0.03133761,  0.04666641, -0.0358191 ,
          0.00192405, -0.01757113],
        [ 0.04517039, -0.0489899 ,  0.01353154,  0.01939956,
         -0.01269288, -0.02680837,  0.02540291,  0.04773739,
         -0.01915524, -0.01975956],
        [ 0.03072823,  0.0249168 , -0.03529322, -0.0

In [ ]:
embedded_docs[0]

In [ ]:
model.predict(embedded_docs[0])